/*
S_BANKS stores static data on banks -> Holding companies
*/
DROP TABLE S_BANKS;
CREATE TABLE S_BANKS
(
	PROCESSING_PERIOD		NUMERIC 		NOT NULL
   ,TXT_BANK_SHORTNAME	VARCHAR(30) 	NOT NULL
   ,TXT_BANK_LONGNAME		VARCHAR(250) 	NOT NULL
   ,COD_BANK_CODE			VARCHAR(10) 	NOT NULL
   ,COD_COUNTRY_DOMICIL	VARCHAR(2) 		NOT NULL
   ,NAM_COUNTRY				VARCHAR(250) 	NOT NULL
   ,COD_BANK_SYS_ID
   ,COD_BIC					VARCHAR(30)		
   ,DAT_RECORD				DATETIME 		DEFAULT CURRENT_TIMESTAMP
   ,UNIQUE (TXT_BANK_SHORTNAME, COD_BANK_CODE, COD_COUNTRY_DOMICIL)
);


/*
S_BANKS_BRANCHES stores static data on branches - foreign branches
*/
DROP TABLE S_BANKS_BRANCHES;
CREATE TABLE S_BANKS_BRANCHES
(	
	 PROCESSING_PERIOD			NUMERIC			NOT NULL
   ,TXT_BANK_SHORTNAME 		VARCHAR(30) 	NOT NULL
   ,TXT_BRANCH_SHORTNAME 	VARCHAR(30) 	NOT NULL
   ,TXT_BRANCH_NAME 			VARCHAR(260) 	NOT NULL
   ,COD_COUNTRY					VARCHAR(2) 		NOT NULL
   ,NAM_COUNTRY					VARCHAR(250) 	NOT NULL
   ,DAT_RECORD					DATETIME 		DEFAULT CURRENT_TIMESTAMP
   ,COD_BIC						VARCHAR(30)
   ,UNIQUE (TXT_BANK_SHORTNAME, TXT_BRANCH_SHORTNAME, COD_COUNTRY)
);

/*
B_TRANSACTIONS stores static data on transactions
*/
DROP TABLE B_TRANSACTIONS
(
	
);